spring:
  application:
    name: boardpjt

  # profile -> dev, prod
  profiles:
    active: dev
  # ???? ??? ???, dev? ???? ???? ??

# ????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true



